; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=aarch64-none-linux-gnu < %s | FileCheck %s

; -smin(X,0) == -(X & M) and -smax(X,0) == -(X & ~M) for the 0/-1 sign mask
; M = (X asr bw-1).  Since M is 0 or -1 the negate distributes onto the AND, so
; these can be emitted as neg ; and/bic(...,asr) with the shift kept on the
; original X, letting the negate and shift issue in parallel.
;
; When the negate instead feeds a comparison it is folded into a cmn, so the
; fold is suppressed there (see neg_smin_cmp / neg_smax_cmp).

define i32 @neg_smin_zero_i32(i32 %x) {
; CHECK-LABEL: neg_smin_zero_i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w8, w0, w0, asr #31
; CHECK-NEXT:    neg w0, w8
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smin.i32(i32 %x, i32 0)
  %n = sub i32 0, %m
  ret i32 %n
}

define i64 @neg_smin_zero_i64(i64 %x) {
; CHECK-LABEL: neg_smin_zero_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and x8, x0, x0, asr #63
; CHECK-NEXT:    neg x0, x8
; CHECK-NEXT:    ret
  %m = call i64 @llvm.smin.i64(i64 %x, i64 0)
  %n = sub i64 0, %m
  ret i64 %n
}

; smin operands commuted (smin 0, X).
define i32 @neg_smin_zero_commuted(i32 %x) {
; CHECK-LABEL: neg_smin_zero_commuted:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w8, w0, w0, asr #31
; CHECK-NEXT:    neg w0, w8
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smin.i32(i32 0, i32 %x)
  %n = sub i32 0, %m
  ret i32 %n
}

define i32 @neg_smax_zero_i32(i32 %x) {
; CHECK-LABEL: neg_smax_zero_i32:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic w8, w0, w0, asr #31
; CHECK-NEXT:    neg w0, w8
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smax.i32(i32 %x, i32 0)
  %n = sub i32 0, %m
  ret i32 %n
}

define i64 @neg_smax_zero_i64(i64 %x) {
; CHECK-LABEL: neg_smax_zero_i64:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic x8, x0, x0, asr #63
; CHECK-NEXT:    neg x0, x8
; CHECK-NEXT:    ret
  %m = call i64 @llvm.smax.i64(i64 %x, i64 0)
  %n = sub i64 0, %m
  ret i64 %n
}

; The negate feeds a comparison, which folds it into a cmn; the fold must not
; fire here or it would cost an extra instruction.
define i32 @neg_smin_cmp(i32 %x, i32 %y) {
; CHECK-LABEL: neg_smin_cmp:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w8, w0, w0, asr #31
; CHECK-NEXT:    neg w8, w8
; CHECK-NEXT:    cmp w8, w1
; CHECK-NEXT:    cset w0, gt
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smin.i32(i32 %x, i32 0)
  %n = sub i32 0, %m
  %c = icmp sgt i32 %n, %y
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @neg_smax_cmp(i32 %x, i32 %y) {
; CHECK-LABEL: neg_smax_cmp:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic w8, w0, w0, asr #31
; CHECK-NEXT:    cmn w1, w8
; CHECK-NEXT:    cset w0, lt
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smax.i32(i32 %x, i32 0)
  %n = sub i32 0, %m
  %c = icmp sgt i32 %n, %y
  %z = zext i1 %c to i32
  ret i32 %z
}

; Equality compares fold the negate into a cmn regardless of INT_MIN (they do
; not read the C/V flags), so smin benefits here too and the fold must stay
; suppressed for it.
define i32 @neg_smin_eq(i32 %x, i32 %y) {
; CHECK-LABEL: neg_smin_eq:
; CHECK:       // %bb.0:
; CHECK-NEXT:    and w8, w0, w0, asr #31
; CHECK-NEXT:    cmn w1, w8
; CHECK-NEXT:    cset w0, eq
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smin.i32(i32 %x, i32 0)
  %n = sub i32 0, %m
  %c = icmp eq i32 %n, %y
  %z = zext i1 %c to i32
  ret i32 %z
}

define i32 @neg_smax_eq(i32 %x, i32 %y) {
; CHECK-LABEL: neg_smax_eq:
; CHECK:       // %bb.0:
; CHECK-NEXT:    bic w8, w0, w0, asr #31
; CHECK-NEXT:    cmn w1, w8
; CHECK-NEXT:    cset w0, eq
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smax.i32(i32 %x, i32 0)
  %n = sub i32 0, %m
  %c = icmp eq i32 %n, %y
  %z = zext i1 %c to i32
  ret i32 %z
}

; Negative test: smin against a non-zero constant is not the sign-mask idiom.
define i32 @neg_smin_nonzero(i32 %x) {
; CHECK-LABEL: neg_smin_nonzero:
; CHECK:       // %bb.0:
; CHECK-NEXT:    mov w8, #5 // =0x5
; CHECK-NEXT:    cmp w0, #5
; CHECK-NEXT:    csel w8, w0, w8, lt
; CHECK-NEXT:    neg w0, w8
; CHECK-NEXT:    ret
  %m = call i32 @llvm.smin.i32(i32 %x, i32 5)
  %n = sub i32 0, %m
  ret i32 %n
}

declare i32 @llvm.smin.i32(i32, i32)
declare i64 @llvm.smin.i64(i64, i64)
declare i32 @llvm.smax.i32(i32, i32)
declare i64 @llvm.smax.i64(i64, i64)
